name: Build & lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  lint_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: yarn
      - name: Build Firefox
        run: yarn build:firefox
      - name: Build Chrome
        run: yarn build:chrome
      - name: Lint
        run: yarn lint